"""
Evaluation and Metrics Calculation Script
Stage 3 of the Hybrid AI Pipeline for Lexicographic Knowledge Extraction

This script compares the structured JSON output generated by the hybrid pipeline (LLM) 
against the manually annotated Gold Standard dataset. It calculates:
- Precision, Recall, and F1-Score (overall and per-field)
- Structural Consistency (% of schema-compliant entries)
- Missing Field Rate
- Inter-Annotator Agreement (Cohen's Kappa) for categorical fields (e.g., Part of Speech)
"""

import json
import argparse
from typing import List, Dict, Tuple
from sklearn.metrics import cohen_kappa_score

def load_json(filepath: str) -> List[Dict]:
    """Loads a JSON file containing a list of lexicographic entries."""
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)

def extract_flat_fields(entry: Dict) -> Dict[str, str]:
    """
    Flattens the hierarchical JSON entry to easily compare specific target fields.
    Extracts the primary fields evaluated in the paper.
    """
    flat = {
        "lemma": entry.get("lemma", "").strip().lower(),
        "part_of_speech": "",
        "definition": "",
        "examples": "",
        "morphology": "",
        "etymology": entry.get("etymology", "").strip().lower()
    }
    
    # Extract POS (Categorical)
    if entry.get("part_of_speech"):
        flat["part_of_speech"] = entry["part_of_speech"][0].strip().lower()
        
    # Extract First Definition and Example
    if entry.get("senses") and len(entry["senses"]) > 0:
        sense = entry["senses"][0]
        flat["definition"] = sense.get("definition", "").strip().lower()
        if sense.get("examples") and len(sense["examples"]) > 0:
            flat["examples"] = sense["examples"][0].get("source_text", "").strip().lower()
            
    # Extract Morphology Root
    if entry.get("morphology") and isinstance(entry["morphology"], dict):
        flat["morphology"] = entry["morphology"].get("root", "").strip().lower()
        
    return flat

def calculate_classification_metrics(true_values: List[str], pred_values: List[str]) -> Tuple[float, float, float]:
    """
    Calculates Precision, Recall, and F1-Score based on exact or partial presence.
    TP: Field present and matches (or is highly similar).
    FP: LLM generated a field that shouldn't be there, or hallucinated wrong info.
    FN: LLM missed a field present in the Gold Standard.
    """
    tp = fp = fn = 0
    
    for t, p in zip(true_values, pred_values):
        t_present = bool(t)
        p_present = bool(p)
        
        if t_present and p_present:
            # In a real rigorous NLP evaluation, you might use ROUGE or exact match.
            # Here we use a simple strict equivalence for demonstration.
            if t == p:
                tp += 1
            else:
                fp += 1  # Hallucination or wrong extraction
                fn += 1  # Missed the correct extraction
        elif p_present and not t_present:
            fp += 1
        elif t_present and not p_present:
            fn += 1
            
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0
    
    return precision, recall, f1

def main():
    parser = argparse.ArgumentParser(description="Calculate Extraction Metrics")
    parser.add_argument("--predictions", type=str, required=True, help="Path to LLM processed JSON file")
    parser.add_argument("--ground_truth", type=str, required=True, help="Path to Gold Standard JSON file")
    args = parser.parse_args()
    
    # Load datasets
    preds = load_json(args.predictions)
    truths = load_json(args.ground_truth)
    
    if len(preds) != len(truths):
        print("Warning: The number of predicted entries does not match the ground truth entries.")
        
    # Assume entries are aligned by index for this script
    aligned_pairs = zip(truths, preds)
    
    metrics_by_field = {
        "lemma": {"true": [], "pred": []},
        "part_of_speech": {"true": [], "pred": []},
        "definition": {"true": [], "pred": []},
        "examples": {"true": [], "pred": []},
        "morphology": {"true": [], "pred": []},
        "etymology": {"true": [], "pred": []},
    }
    
    structural_failures = 0
    total_fields_expected = 0
    total_fields_missing = 0
    
    for truth, pred in aligned_pairs:
        # 1. Structural Consistency Check
        if pred.get("_schema_valid") is False:
            structural_failures += 1
            
        flat_truth = extract_flat_fields(truth)
        flat_pred = extract_flat_fields(pred)
        
        # 2. Populate vectors for Precision/Recall and Missing Rates
        for field in metrics_by_field.keys():
            t_val = flat_truth[field]
            p_val = flat_pred[field]
            
            metrics_by_field[field]["true"].append(t_val)
            metrics_by_field[field]["pred"].append(p_val)
            
            if bool(t_val):
                total_fields_expected += 1
                if not bool(p_val):
                    total_fields_missing += 1

    # --- Print Evaluation Report ---
    print("\n" + "="*50)
    print(" LEXICOGRAPHIC EXTRACTION EVALUATION REPORT")
    print("="*50)
    
    # 1. Overall System Metrics
    consistency = ((len(preds) - structural_failures) / len(preds)) * 100
    missing_rate = (total_fields_missing / total_fields_expected) * 100 if total_fields_expected > 0 else 0
    
    print(f"\n[System-Level Metrics]")
    print(f"Total Entries Evaluated : {len(preds)}")
    print(f"Structural Consistency  : {consistency:.1f}%")
    print(f"Missing Field Rate      : {missing_rate:.1f}%")
    
    # 2. Inter-Annotator Agreement (Cohen's Kappa) on Categorical Field
    # We use Part of Speech as the representative categorical field
    kappa = cohen_kappa_score(
        metrics_by_field["part_of_speech"]["true"], 
        metrics_by_field["part_of_speech"]["pred"]
    )
    print(f"Cohen's Kappa (POS)     : {kappa:.3f}")
    
    # 3. Granular Metrics by Lexical Field
    print("\n[Granular Extraction Performance]")
    print(f"{'Lexical Field':<18} | {'Precision':<10} | {'Recall':<10} | {'F1-Score':<10}")
    print("-" * 55)
    
    macro_p, macro_r, macro_f1 = 0, 0, 0
    num_fields = len(metrics_by_field)
    
    for field, data in metrics_by_field.items():
        p, r, f1 = calculate_classification_metrics(data["true"], data["pred"])
        
        macro_p += p
        macro_r += r
        macro_f1 += f1
        
        print(f"{field.capitalize():<18} | {p*100:>8.1f}% | {r*100:>8.1f}% | {f1*100:>8.1f}%")
        
    print("-" * 55)
    print(f"{'MACRO AVERAGE':<18} | {(macro_p/num_fields)*100:>8.1f}% | {(macro_r/num_fields)*100:>8.1f}% | {(macro_f1/num_fields)*100:>8.1f}%")
    print("="*50 + "\n")

if __name__ == "__main__":
    main()