"""
LLM Semantic Completion and Inference Script
Stage 2 of the Hybrid AI Pipeline for Lexicographic Knowledge Extraction

This script processes the intermediate JSON entries generated by the rule-based parser.
It loads Qwen2.5-72B-Instruct using 4-bit quantization (AWQ/GPTQ) and CPU-GPU offloading.
It applies deterministic inference (Greedy Decoding, Temp 0.0, Seed 42) to map implicit 
semantic information into the target JSON schema, and validates the output automatically.
"""

import os
import re
import json
import torch
import argparse
import jsonschema
from pathlib import Path
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer

def setup_deterministic_environment(seed: int = 42):
    """Sets random seeds for reproducibility."""
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

def load_model_and_tokenizer(model_id: str = "Qwen/Qwen2.5-72B-Instruct-AWQ"):
    """
    Loads the quantized model using Hugging Face Accelerate for CPU-GPU offloading.
    Requires device_map="auto" to distribute the 72B model across VRAM and System RAM.
    """
    print(f"Loading tokenizer: {model_id}")
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    
    print(f"Loading quantized model with offloading: {model_id}")
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        device_map="auto",              # Enables CPU-GPU offloading
        torch_dtype=torch.float16,      # Optimized precision for inference
        low_cpu_mem_usage=True          # Prevents RAM spikes during loading
    )
    
    return model, tokenizer

def extract_json_from_response(response_text: str) -> dict:
    """Extracts a JSON object from the LLM's raw output string."""
    # Try to find JSON block if the model outputs markdown formatting
    json_match = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', response_text, re.DOTALL)
    if json_match:
        response_text = json_match.group(1)
        
    try:
        return json.loads(response_text)
    except json.JSONDecodeError as e:
        print(f"JSON Decoding Error: {e}")
        return None

def process_entries(
    input_path: Path, 
    output_path: Path, 
    model, 
    tokenizer, 
    schema: dict, 
    system_prompt: str, 
    user_prompt_template: str
):
    """Iterates through interim entries, queries the LLM, and validates the output."""
    with open(input_path, 'r', encoding='utf-8') as f:
        interim_data = json.load(f)
        
    processed_data = []
    structural_failures = 0
    
    print(f"Processing {len(interim_data)} entries from {input_path.name}...")
    
    for entry in tqdm(interim_data):
        raw_text = entry.get("raw_text", "")
        
        # Format the user prompt with the raw entry
        user_content = user_prompt_template.replace("{{RAW_DICTIONARY_ENTRY}}", raw_text)
        
        # Build ChatML format for Qwen
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content}
        ]
        
        text = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )
        
        model_inputs = tokenizer([text], return_tensors="pt").to(model.device)
        
        # Deterministic Generation Parameters (Greedy Decoding)
        with torch.no_grad():
            generated_ids = model.generate(
                model_inputs.input_ids,
                max_new_tokens=4096,
                temperature=0.0,       # Strict deterministic decoding
                do_sample=False,       # Greedy decoding (forces top-p to be ignored)
                pad_token_id=tokenizer.eos_token_id
            )
            
        generated_ids = [
            output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
        ]
        
        response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
        
        # Extract and validate JSON
        extracted_json = extract_json_from_response(response)
        
        if extracted_json:
            try:
                jsonschema.validate(instance=extracted_json, schema=schema)
                # Validation passed, append to results
                processed_data.append(extracted_json)
            except jsonschema.exceptions.ValidationError as e:
                print(f"Schema Validation Error on entry '{entry.get('lemma')}': {e.message}")
                structural_failures += 1
                # Fallback: append the extracted JSON anyway but flag it
                extracted_json["_schema_valid"] = False
                processed_data.append(extracted_json)
        else:
            print(f"Failed to extract JSON for entry '{entry.get('lemma')}'.")
            structural_failures += 1
            
    # Export final structured data
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(processed_data, f, ensure_ascii=False, indent=4)
        
    print(f"Finished processing. Structural failures: {structural_failures}/{len(interim_data)}")
    print(f"Saved results to {output_path}")

def main():
    parser = argparse.ArgumentParser(description="LLM Semantic Completion using Qwen2.5")
    parser.add_argument("--input", type=str, required=True, help="Directory containing interim JSON files")
    parser.add_argument("--output", type=str, required=True, help="Directory to save final processed JSON files")
    parser.add_argument("--schema", type=str, default="schema/target_schema.json", help="Path to JSON schema file")
    parser.add_argument("--system_prompt", type=str, default="prompts/system_prompt.txt", help="Path to system prompt")
    parser.add_argument("--user_prompt", type=str, default="prompts/user_prompt.txt", help="Path to user prompt template")
    args = parser.parse_args()
    
    # 1. Setup deterministic environment
    setup_deterministic_environment(seed=42)
    
    # 2. Load Prompts and Schema
    with open(args.schema, 'r', encoding='utf-8') as f:
        schema = json.load(f)
    with open(args.system_prompt, 'r', encoding='utf-8') as f:
        system_prompt = f.read()
    with open(args.user_prompt, 'r', encoding='utf-8') as f:
        user_prompt_template = f.read()
        
    # 3. Load Model
    model, tokenizer = load_model_and_tokenizer()
    
    input_dir = Path(args.input)
    output_dir = Path(args.output)
    
    if not input_dir.exists():
        print(f"Error: Input directory {input_dir} does not exist.")
        return
        
    # 4. Process all interim files
    for json_file in input_dir.glob("*_interim.json"):
        output_file = output_dir / f"{json_file.stem.replace('_interim', '_final')}.json"
        process_entries(json_file, output_file, model, tokenizer, schema, system_prompt, user_prompt_template)

if __name__ == "__main__":
    main()